export enum AUTH_ERROR_CODES {
  WALLET_NOT_FOUND = 'AUTH_001',
  NETWORK_MISMATCH = 'AUTH_002',
  INVALID_SIGNATURE = 'AUTH_003',
  SESSION_EXPIRED = 'AUTH_004',
  FIREBASE_ERROR = 'AUTH_005',
  TWO_FACTOR_REQUIRED = 'AUTH_006',
  TWO_FACTOR_INVALID = 'AUTH_007',
  WALLET_DISCONNECTED = 'AUTH_008',
  PROVIDER_ERROR = 'AUTH_009',
  EMAIL_NOT_VERIFIED = 'auth/email-not-verified',
  EMAIL_VERIFICATION_TIMEOUT = 'auth/verification-timeout',
  NO_USER = 'AUTH_010',
  STORAGE_ERROR = 'AUTH_011'
}
