# This file is intentionally minimal to fix warnings
# The original file was causing warnings but was not found in the project

name: DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a placeholder workflow"
